#!/usr/bin/env bash
# PreToolUse guard for Edit/Write: refuse to hand-edit files that a generator,
# a package manager, or release-please owns. Every rule here restates a "never
# hand-edit" line from AGENTS.md that is otherwise enforced only by an agent
# remembering to read it.
#
# Exit 2 blocks the tool call and feeds stderr back to Claude. Anything else
# allows it — this fails OPEN on purpose (a missing jq must not block real work).
set -uo pipefail

payload=$(cat)
file=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty' 2>/dev/null)
[ -n "$file" ] || exit 0

rel=${file#"${CLAUDE_PROJECT_DIR:-$PWD}/"}

block() {
  printf '%s\n' "$1" >&2
  exit 2
}

case "$rel" in
CHANGELOG.md | .release-please-manifest.json)
  block "release-please owns $rel (AGENTS.md → Releases). To force a version, add a 'Release-As: x.y.z' footer to a commit instead." ;;
src/db/migrations/*)
  block "drizzle-kit owns $rel. Edit src/db/schema.ts, run 'bun run db:generate', and commit the generated output." ;;
src/uniwind-types.d.ts | expo-env.d.ts | .expo/types/*)
  block "$rel is generated (Metro / expo-router typed routes) and gitignored. Regenerate it by starting the dev server once. Never hand-write it, and never copy it from another checkout — it encodes that branch's routes." ;;
ios/*)
  block "ios/ is generated by prebuild (Continuous Native Generation) and gitignored — edits are lost on the next prebuild. Configure this through app.json / app.config.ts or a config plugin." ;;
bun.lock)
  block "bun.lock is written by Bun. Change dependencies with 'bun expo install <pkg>' (Expo-compatible versions) or 'bun install'." ;;
esac

# package.json / app.json are editable in general, but two fields inside them
# are not: `version` belongs to release-please, and a corepack-injected
# `packageManager` pin makes EAS Build and the e2e-ios job honour yarn over
# bun.lock.
case "$rel" in
package.json | app.json)
  incoming=$(printf '%s' "$payload" |
    jq -r '[.tool_input.new_string, .tool_input.content] | map(select(. != null)) | join("\n")' 2>/dev/null)
  case "$incoming" in
  *'"version"'*)
    block "release-please owns the version field in $rel (AGENTS.md → Releases). Use a 'Release-As: x.y.z' commit footer instead of editing it." ;;
  *'"packageManager"'*)
    block "Never add a packageManager field — a yarn pin makes EAS Build / the e2e-ios job ignore bun.lock and break (AGENTS.md). If corepack injected it, delete it and set COREPACK_ENABLE_AUTO_PIN=0." ;;
  esac
  ;;
esac

exit 0
